CREATE DATABASE IF NOT EXISTS reserva_quadras_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE reserva_quadras_db;

CREATE TABLE IF NOT EXISTS reservas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  vagas INT NOT NULL,
  preco DECIMAL(10,2) NOT NULL,
  horario DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
